name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository's code

      - name: Merge main into gh-pages
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git pull origin gh-pages
          git merge origin/main --allow-unrelated-histories -X theirs --no-edit -m "Merge main into gh-pages"
          git push origin gh-pages